### ISSUE TITLE
Hardcoded PI constant

### ISSUE THREAD

**Issue by EmanueleGhelfi** [ricber/relocalization_evaluation#2]
Here https://github.com/ricber/relocalization_evaluation/blob/master/relocalization_error.cpp#L57 you've hardcoded the PI constant. I think it is better to use the constant provided by some framework. Maybe the PI from the standard library?

**Comment by ricber** [comment]
Thank you very much @EmanueleGhelfi for the suggestion! I'm going to implement it in the next release.
